name: Update Wiki

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: alexiva0/test-wiki.wiki    # the wiki repo name.
      - name: Print files
        run: |
          ls -la
      - name: Edit wiki
        run: |
          echo "My own cool text pushed with GITHUB_TOKEN" > Home.md
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add changes"
      - name: Push changes to wiki repo
        run: |
          git push "https://alexiva0:${secrets.GITHUB_TOKEN}@github.com/alexiva0/test-wiki.wiki.git" HEAD:master
